version: '3.1'

services:
  database:
    container_name: techsolutio_db
    image: mysql
    command: --authentication_policy=mysql_native_password
    ports:
      - 3306:3306
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - techsolutio:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

volumes:
  techsolutio: